name: Build binaries

on:
  push:
    branches:
      - 'release-*'
      - 'v*'
    tags:
      - 'v*'

defaults:
  run:
    shell: bash

jobs:
  Build:
    name: Build release binaries

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip pyinstaller
          pip install -r requirements.txt

      - name: Build with pyinstaller
        run: pyinstaller --onefile --name=torrserver_series_updater-${{ matrix.os }} series_updater.py

      - name: Deploy artifacts
        uses: actions/upload-artifact@v2
        with:
          name: torrserver_series_updater-${{ matrix.os }}
          path: dist/torrserver_series_updater-${{ matrix.os }}*
          if-no-files-found: error
