name: Docker Image release

on:
  push:
    branches:
      - 'release-*'

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      DOCKER_REPO: ${{ secrets.DOCKER_REPO }}

    steps:
    - uses: actions/checkout@v3

    - name: 'Get tag'
      id: tag
      uses: 'WyriHaximus/github-action-get-previous-tag@8a0e045f02c0a3a04e1452df58b90fc7e555e950'

    - name: Set correct environment
      run: |
        TAG=${{ steps.tag.outputs.tag }}
        echo "TAG=$TAG" >> "$GITHUB_ENV"

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Docker login
      run: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin

    - name: Build the Docker image
      run: docker buildx build . --push --file Dockerfile --tag $DOCKER_USER/$DOCKER_REPO --tag $DOCKER_USER/$DOCKER_REPO:$TAG --platform linux/amd64,linux/arm64,linux/arm/v7
