name: Docker Image release

on:
  push:
    branches:
      - 'release-*'
      - 'v*'
#    tags:
#      - 'v*'

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      DOCKER_REPO: ${{ secrets.DOCKER_REPO }}

    steps:
    - uses: actions/checkout@v3

    - name: Docker login
      run: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Docker meta
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v1
      with:
        images: ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPO }}
        tag-custom: latest
        tag-semver: |
          {{raw}}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}

#    - name: Set up Docker Buildx
#      id: buildx
#      uses: docker/setup-buildx-action@v1
#
#    - name: Build the Docker image
#      run: docker buildx build . --push --file Dockerfile --tag $DOCKER_USER/$DOCKER_REPO --tag $DOCKER_USER/$DOCKER_REPO:$TAG --platform linux/amd64,linux/arm64,linux/arm/v7
