on:
  push:
    branches:
      - 'release-*'

jobs:
  docker:
    name: Publish - Docker Hub
    runs-on: ubuntu-latest
    env:
      REPO: ${{ secrets.DOCKER_REPO }}
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Build Docker image
        run: docker build --file Dockerfile --tag $REPO:latest --tag $REPO:${GITHUB_SHA::8} .
      - name: Publish Docker image
        run: docker push $REPO
